default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rabbitmq_consumer_development_<%=ENV['QUEUE_ID']%>
test:
  <<: *default
  database: rabbitmq-consumer_test_<%=ENV['QUEUE_ID']%>
production:
  <<: *default
  database: rabbitmq-consumer_production
  username: rabbitmq-consumer
  password: <%= ENV['RABBITMQ-CONSUMER_DATABASE_PASSWORD'] %>
